# ------------------------------------------------------------
# Experiment selection
# ------------------------------------------------------------
experiment_case: "SYBIL_ONLY"

# ------------------------------------------------------------
# Attackers
# ------------------------------------------------------------
attacker_ids:
  - "client_2"
  - "client_3"
  - "client_5"
# 
# ============================================================

# ------------------------------------------------------------
# FL Runtime Config
# ------------------------------------------------------------
num_rounds: 10
local_epochs: 5
seed: 2709
enable_prover: true

# ============================================================
# Attack options
# ============================================================


# ------------------------------------------------------------
# Sybil Attack
# ------------------------------------------------------------
sybil_mode: "static"        # static | leader | coordinated
alpha: 0.8                  # smoothing factor (for coordinated mode)
sybil_collusion: false
sybil_use_grad: "NONE"  
sybil_fake_data_size: 400
sybil_history_window: 5
sybil_amplification_factor: 1.0
# ============================================================